---

# Main tasks file for secrets role

# Manage CA cert files
- name: 'Manage CA certificate files deployment'
  include: "{{ role_path }}/tasks/manage_ca_certificates.yml"
  no_log: True

# Manage private SSL files
- name: 'Manage private SSL files deployment'
  include: "{{ role_path }}/tasks/manage_private_ssl.yml"
  no_log: True

# Manage SSH private key files
- name: 'Manage SSH private key files deployment'
  include: "{{ role_path }}/tasks/manage_ssh_private_keys.yml"
  no_log: True
